/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsx createPlasmicElementProxy */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4p2NHB7HnAYV45yx1ZgrVt
// Component: yoBg6XMOMn8SaW
import * as React from "react";
import {
  hasVariant,
  createPlasmicElement,
  RenderOpts,
  Override,
  classNames,
  Flex,
  wrapWithClassName,
  Renderer,
  NodeRenderer,
  createPlasmicElementProxy,
  makeFragment,
  PlasmicIcon,
  PlasmicSlot,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger
} from "@plasmicapp/react-web";

import { ThemeContext, ThemeValue } from "../PlasmicGlobalVariant__Theme"; // plasmic-import: qBJztiWboOaDz9/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_todo_mvc_for_tutorial_work.css"; // plasmic-import: 4p2NHB7HnAYV45yx1ZgrVt/projectcss
import "./PlasmicTask.css"; // plasmic-import: yoBg6XMOMn8SaW/css

export type PlasmicTask__VariantsArgs = {
  state?: SingleChoiceArg<"checked" | "editing">;
};

export const PlasmicTask__VariantProps: (keyof PlasmicTask__VariantsArgs)[] = [
  "state"
];

export type PlasmicTask__ArgsType = {
  children?: React.ReactNode;
};

export const PlasmicTask__ArgProps: (keyof PlasmicTask__ArgsType)[] = [
  "children"
];

export interface DefaultTaskProps {
  children?: React.ReactNode;
  state?: SingleChoiceArg<"checked" | "editing">;
  className?: string;
}

const PlasmicTask__RenderFuncs = {
  root: (
    opts: RenderOpts<
      PlasmicTask__VariantsArgs,
      PlasmicTask__ArgsType,
      {
        root?: Flex<"div">;
        checkbox?: Flex<"div">;
        img?: Flex<"img">;
        label?: Flex<"div">;
        textbox?: Flex<"input">;
        deleteBtn?: Flex<"button">;
      }
    >
  ): React.ReactElement | null => {
    return <PlasmicTask__FCs.root opts={opts} />;
  },
  checkbox: (
    opts: RenderOpts<
      PlasmicTask__VariantsArgs,
      PlasmicTask__ArgsType,
      {
        checkbox?: Flex<"div">;
        img?: Flex<"img">;
      }
    >
  ): React.ReactElement | null => {
    return <PlasmicTask__FCs.checkbox opts={opts} />;
  },
  img: (
    opts: RenderOpts<
      PlasmicTask__VariantsArgs,
      PlasmicTask__ArgsType,
      {
        img?: Flex<"img">;
      }
    >
  ): React.ReactElement | null => {
    return <PlasmicTask__FCs.img opts={opts} />;
  },
  label: (
    opts: RenderOpts<
      PlasmicTask__VariantsArgs,
      PlasmicTask__ArgsType,
      {
        label?: Flex<"div">;
      }
    >
  ): React.ReactElement | null => {
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};
    return (hasVariant(variants, "state", "editing") ? false : true) ? (
      <div
        data-plasmic-override={overrides.label}
        className={classNames({
          "Task__label--checked___z7LFV94sI": hasVariant(
            variants,
            "state",
            "checked"
          ),

          "Task__label--editing___z7LFURfc1": hasVariant(
            variants,
            "state",
            "editing"
          ),

          Task__label___z7LF: true,
          "plasmic-default__all": true,
          "plasmic-default__div": true
        })}
      >
        {PlasmicTask__RenderFuncs.slotChildren({
          variants,
          args,
          overrides
        })}
      </div>
    ) : null;
  },
  slotChildren: (
    opts: RenderOpts<PlasmicTask__VariantsArgs, PlasmicTask__ArgsType, {}>
  ): React.ReactElement | null => {
    return <PlasmicTask__FCs.slotChildren opts={opts} />;
  },
  textbox: (
    opts: RenderOpts<
      PlasmicTask__VariantsArgs,
      PlasmicTask__ArgsType,
      {
        textbox?: Flex<"input">;
      }
    >
  ): React.ReactElement | null => {
    return <PlasmicTask__FCs.textbox opts={opts} />;
  },
  deleteBtn: (
    opts: RenderOpts<
      PlasmicTask__VariantsArgs,
      PlasmicTask__ArgsType,
      {
        deleteBtn?: Flex<"button">;
      }
    >
  ): React.ReactElement | null => {
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};
    return (
      <button
        data-plasmic-override={overrides.deleteBtn}
        className={classNames({
          "Task__deleteBtn--editing__d92j2URfc1": hasVariant(
            variants,
            "state",
            "editing"
          ),

          Task__deleteBtn__d92j2: true,
          "plasmic-default__all": true,
          "plasmic-default__button": true
        })}
      >
        {"×"}
      </button>
    );
  }
};

const PlasmicTask__FCs = {
  root: ((props: {
    opts: Parameters<typeof PlasmicTask__RenderFuncs["root"]>[0];
  }) => {
    const { opts } = props;
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};

    const globalVariants = {
      theme: React.useContext(ThemeContext)
    };

    return (
      <div
        data-plasmic-override={overrides.root}
        className={classNames({
          "Task__root--baseDark__mRJK3Rlyu__6DHL0":
            true && hasVariant(globalVariants, "theme", "dark"),
          "Task__root--checked__mRJK3V94sI": hasVariant(
            variants,
            "state",
            "checked"
          ),

          "Task__root--editing__mRJK3URfc1": hasVariant(
            variants,
            "state",
            "editing"
          ),

          Task__root__mRJK3: true,
          "plasmic-default__all": true,
          "plasmic-default__div": true
        })}
      >
        <div
          className={classNames({
            "Task__box--editingDark__FhmyKURfc1_6DHL0":
              hasVariant(variants, "state", "editing") &&
              hasVariant(globalVariants, "theme", "dark"),
            "Task__box--editing__FhmyKURfc1": hasVariant(
              variants,
              "state",
              "editing"
            ),

            Task__box__FhmyK: true,
            "plasmic-default__all": true,
            "plasmic-default__div": true
          })}
        >
          {PlasmicTask__RenderFuncs.checkbox({
            variants,
            args,
            overrides
          })}
        </div>

        <div
          className={classNames({
            "Task__box--baseDark__oSxEGRlyu__6DHL0":
              true && hasVariant(globalVariants, "theme", "dark"),
            "Task__box--editingDark__oSxEGURfc1_6DHL0":
              hasVariant(variants, "state", "editing") &&
              hasVariant(globalVariants, "theme", "dark"),
            "Task__box--editing__oSxEGURfc1": hasVariant(
              variants,
              "state",
              "editing"
            ),

            Task__box__oSxEG: true,
            "plasmic-default__all": true,
            "plasmic-default__div": true
          })}
        >
          {PlasmicTask__RenderFuncs.label({
            variants,
            args,
            overrides
          })}

          {PlasmicTask__RenderFuncs.textbox({
            variants,
            args,
            overrides
          })}

          {(hasVariant(variants, "state", "editing") ? false : true) ? (
            <div
              className={classNames({
                "Task__box--editing__mWqXjURfc1": hasVariant(
                  variants,
                  "state",
                  "editing"
                ),

                Task__box__mWqXj: true,
                "plasmic-default__all": true,
                "plasmic-default__div": true
              })}
            >
              {PlasmicTask__RenderFuncs.deleteBtn({
                variants,
                args,
                overrides
              })}
            </div>
          ) : null}
        </div>
      </div>
    ) as React.ReactElement;
  }) as React.FunctionComponent<{
    opts: Parameters<typeof PlasmicTask__RenderFuncs["root"]>[0];
  }>,

  checkbox: ((props: {
    opts: Parameters<typeof PlasmicTask__RenderFuncs["checkbox"]>[0];
  }) => {
    const { opts } = props;
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};

    const globalVariants = {
      theme: React.useContext(ThemeContext)
    };

    return ((hasVariant(variants, "state", "editing") ? false : true) ? (
      <div
        data-plasmic-override={overrides.checkbox}
        className={classNames({
          "Task__checkbox--checkedDark__HCB5IV94sI_6DHL0":
            hasVariant(variants, "state", "checked") &&
            hasVariant(globalVariants, "theme", "dark"),
          "Task__checkbox--checked__HCB5IV94sI": hasVariant(
            variants,
            "state",
            "checked"
          ),

          "Task__checkbox--editing__HCB5IURfc1": hasVariant(
            variants,
            "state",
            "editing"
          ),

          Task__checkbox__HCB5I: true,
          "plasmic-default__all": true,
          "plasmic-default__div": true
        })}
      >
        {PlasmicTask__RenderFuncs.img({
          variants,
          args,
          overrides
        })}
      </div>
    ) : null) as React.ReactElement;
  }) as React.FunctionComponent<{
    opts: Parameters<typeof PlasmicTask__RenderFuncs["checkbox"]>[0];
  }>,

  img: ((props: {
    opts: Parameters<typeof PlasmicTask__RenderFuncs["img"]>[0];
  }) => {
    const { opts } = props;
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};

    const globalVariants = {
      theme: React.useContext(ThemeContext)
    };

    return ((hasVariant(variants, "state", "checked") ? true : false) ? (
      <img
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames({
          "Task__img--checkedDark__uJa5lV94sI_6DHL0":
            hasVariant(variants, "state", "checked") &&
            hasVariant(globalVariants, "theme", "dark"),
          "Task__img--checked__uJa5lV94sI": hasVariant(
            variants,
            "state",
            "checked"
          ),

          "Task__img--editing__uJa5lURfc1": hasVariant(
            variants,
            "state",
            "editing"
          ),

          Task__img__uJa5l: true,
          "plasmic-default__all": true,
          "plasmic-default__img": true
        })}
        role={"img"}
        src={
          hasVariant(variants, "state", "checked")
            ? ("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgNTEyIDUxMiIgc3Ryb2tlLXdpZHRoPSIwIiBmaWxsPSJjdXJyZW50Q29sb3IiIHN0cm9rZT0iY3VycmVudENvbG9yIiBzdHlsZT0iZmlsbDogcmdiKDQsIDE0MywgNjQpOyI+PHBhdGggZD0iTTE3My44OTggNDM5LjQwNGwtMTY2LjQtMTY2LjRjLTkuOTk3LTkuOTk3LTkuOTk3LTI2LjIwNiAwLTM2LjIwNGwzNi4yMDMtMzYuMjA0YzkuOTk3LTkuOTk4IDI2LjIwNy05Ljk5OCAzNi4yMDQgMEwxOTIgMzEyLjY5IDQzMi4wOTUgNzIuNTk2YzkuOTk3LTkuOTk3IDI2LjIwNy05Ljk5NyAzNi4yMDQgMGwzNi4yMDMgMzYuMjA0YzkuOTk3IDkuOTk3IDkuOTk3IDI2LjIwNiAwIDM2LjIwNGwtMjk0LjQgMjk0LjQwMWMtOS45OTggOS45OTctMjYuMjA3IDkuOTk3LTM2LjIwNC0uMDAxeiIvPjwvc3ZnPg==" as const)
            : ("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgNTEyIDUxMiIgc3Ryb2tlLXdpZHRoPSIwIiBmaWxsPSJjdXJyZW50Q29sb3IiIHN0cm9rZT0iY3VycmVudENvbG9yIj48cGF0aCBkPSJNMTczLjg5OCA0MzkuNDA0bC0xNjYuNC0xNjYuNGMtOS45OTctOS45OTctOS45OTctMjYuMjA2IDAtMzYuMjA0bDM2LjIwMy0zNi4yMDRjOS45OTctOS45OTggMjYuMjA3LTkuOTk4IDM2LjIwNCAwTDE5MiAzMTIuNjkgNDMyLjA5NSA3Mi41OTZjOS45OTctOS45OTcgMjYuMjA3LTkuOTk3IDM2LjIwNCAwbDM2LjIwMyAzNi4yMDRjOS45OTcgOS45OTcgOS45OTcgMjYuMjA2IDAgMzYuMjA0bC0yOTQuNCAyOTQuNDAxYy05Ljk5OCA5Ljk5Ny0yNi4yMDcgOS45OTctMzYuMjA0LS4wMDF6Ii8+PC9zdmc+" as const)
        }
      ></img>
    ) : null) as React.ReactElement;
  }) as React.FunctionComponent<{
    opts: Parameters<typeof PlasmicTask__RenderFuncs["img"]>[0];
  }>,

  label: undefined,
  slotChildren: ((props: {
    opts: Parameters<typeof PlasmicTask__RenderFuncs["slotChildren"]>[0];
  }) => {
    const { opts } = props;
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};

    const globalVariants = {
      theme: React.useContext(ThemeContext)
    };

    return (
      <PlasmicSlot
        defaultContents={"Some kind of text here"}
        value={args.children}
        className={classNames({
          "Task__slotChildren--baseDark__MC9tdRlyu__6DHL0":
            true && hasVariant(globalVariants, "theme", "dark"),
          "Task__slotChildren--checkedDark__MC9tdV94sI_6DHL0":
            hasVariant(variants, "state", "checked") &&
            hasVariant(globalVariants, "theme", "dark"),
          "Task__slotChildren--checked__MC9tdV94sI": hasVariant(
            variants,
            "state",
            "checked"
          ),

          "Task__slotChildren--editing__MC9tdURfc1": hasVariant(
            variants,
            "state",
            "editing"
          ),

          Task__slotChildren__MC9td: true
        })}
      />
    ) as React.ReactElement;
  }) as React.FunctionComponent<{
    opts: Parameters<typeof PlasmicTask__RenderFuncs["slotChildren"]>[0];
  }>,

  textbox: ((props: {
    opts: Parameters<typeof PlasmicTask__RenderFuncs["textbox"]>[0];
  }) => {
    const { opts } = props;
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};

    const globalVariants = {
      theme: React.useContext(ThemeContext)
    };

    return ((hasVariant(variants, "state", "editing") ? true : false) ? (
      <input
        data-plasmic-override={overrides.textbox}
        className={classNames({
          "Task__textbox--editingDark__RNfuwURfc1_6DHL0":
            hasVariant(variants, "state", "editing") &&
            hasVariant(globalVariants, "theme", "dark"),
          "Task__textbox--editing__RNfuwURfc1": hasVariant(
            variants,
            "state",
            "editing"
          ),

          Task__textbox__RNfuw: true,
          "plasmic-default__all": true,
          "plasmic-default__input": true
        })}
        placeholder={"Some placeholder text" as const}
        type={"text" as const}
      ></input>
    ) : null) as React.ReactElement;
  }) as React.FunctionComponent<{
    opts: Parameters<typeof PlasmicTask__RenderFuncs["textbox"]>[0];
  }>,

  deleteBtn: undefined
};

class PlasmicTask__Renderer extends Renderer<
  PlasmicTask__VariantsArgs,
  PlasmicTask__ArgsType,
  typeof PlasmicTask__RenderFuncs,
  "root"
> {
  constructor(
    variants: PlasmicTask__VariantsArgs,
    args: PlasmicTask__ArgsType
  ) {
    super(variants, args, PlasmicTask__RenderFuncs, "root");
  }

  protected create(
    variants: PlasmicTask__VariantsArgs,
    args: PlasmicTask__ArgsType
  ) {
    return new PlasmicTask__Renderer(variants, args);
  }

  getInternalVariantProps(): (keyof PlasmicTask__VariantsArgs)[] {
    return PlasmicTask__VariantProps;
  }

  getInternalArgProps(): (keyof PlasmicTask__ArgsType)[] {
    return PlasmicTask__ArgProps;
  }

  forNode(name: "root"): NodeRenderer<typeof PlasmicTask__RenderFuncs["root"]>;
  forNode(
    name: "checkbox"
  ): NodeRenderer<typeof PlasmicTask__RenderFuncs["checkbox"]>;
  forNode(name: "img"): NodeRenderer<typeof PlasmicTask__RenderFuncs["img"]>;
  forNode(
    name: "label"
  ): NodeRenderer<typeof PlasmicTask__RenderFuncs["label"]>;
  forNode(
    name: "slotChildren"
  ): NodeRenderer<typeof PlasmicTask__RenderFuncs["slotChildren"]>;
  forNode(
    name: "textbox"
  ): NodeRenderer<typeof PlasmicTask__RenderFuncs["textbox"]>;
  forNode(
    name: "deleteBtn"
  ): NodeRenderer<typeof PlasmicTask__RenderFuncs["deleteBtn"]>;
  forNode(name: keyof typeof PlasmicTask__RenderFuncs) {
    return super.forNode(name);
  }
}

type PlasmicTaskRootProps = PlasmicTask__VariantsArgs &
  PlasmicTask__ArgsType & {
    variants?: PlasmicTask__VariantsArgs;
    args?: PlasmicTask__ArgsType;
    overrides?: {
      root?: Flex<"div">;
      checkbox?: Flex<"div">;
      img?: Flex<"img">;
      label?: Flex<"div">;
      textbox?: Flex<"input">;
      deleteBtn?: Flex<"button">;
    };

    root?: Flex<"div">;
    checkbox?: Flex<"div">;
    img?: Flex<"img">;
    label?: Flex<"div">;
    textbox?: Flex<"input">;
    deleteBtn?: Flex<"button">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicTask__VariantsArgs
    | keyof PlasmicTask__ArgsType
    | "variants"
    | "args"
    | "root"
    | "checkbox"
    | "img"
    | "label"
    | "textbox"
    | "deleteBtn"
  >;

export const PlasmicTask = ((props: PlasmicTaskRootProps) => {
  const renderer = new PlasmicTask__Renderer({}, {});
  const descendantNames = [
    "root",
    "checkbox",
    "img",
    "label",
    "textbox",
    "deleteBtn"
  ] as const;
  const leftoverProps = omit(
    props,
    "variants",
    "args",
    "overrides",
    ...descendantNames,
    ...renderer.getInternalVariantProps(),
    ...renderer.getInternalArgProps()
  ) as Partial<React.ComponentProps<"div">>;

  let nodeRenderer = renderer
    .forNode("root")
    .withVariants(pick(props, ...renderer.getInternalVariantProps()))
    .withVariants(props.variants || {})
    .withArgs(pick(props, ...renderer.getInternalArgProps()))
    .withArgs(props.args || {})
    .withOverrides(pick(props, ...descendantNames))
    .withOverrides(props.overrides || {});

  if (Object.keys(leftoverProps).length > 0) {
    nodeRenderer = nodeRenderer.withOverrides({
      root: {
        props: leftoverProps
      }
    });
  }

  return nodeRenderer.render();
}) as React.FunctionComponent<PlasmicTaskRootProps> & {
  checkbox: React.FunctionComponent<PlasmicTaskCheckboxProps>;
  img: React.FunctionComponent<PlasmicTaskImgProps>;
  label: React.FunctionComponent<PlasmicTaskLabelProps>;
  textbox: React.FunctionComponent<PlasmicTaskTextboxProps>;
  deleteBtn: React.FunctionComponent<PlasmicTaskDeleteBtnProps>;
  createRenderer: () => PlasmicTask__Renderer;
};

type PlasmicTaskCheckboxProps = PlasmicTask__VariantsArgs &
  PlasmicTask__ArgsType & {
    variants?: PlasmicTask__VariantsArgs;
    args?: PlasmicTask__ArgsType;
    overrides?: {
      checkbox?: Flex<"div">;
      img?: Flex<"img">;
    };

    checkbox?: Flex<"div">;
    img?: Flex<"img">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicTask__VariantsArgs
    | keyof PlasmicTask__ArgsType
    | "variants"
    | "args"
    | "checkbox"
    | "img"
  >;

PlasmicTask.checkbox = ((props: PlasmicTaskCheckboxProps) => {
  const renderer = new PlasmicTask__Renderer({}, {});
  const descendantNames = ["checkbox", "img"] as const;
  const leftoverProps = omit(
    props,
    "variants",
    "args",
    "overrides",
    ...descendantNames,
    ...renderer.getInternalVariantProps(),
    ...renderer.getInternalArgProps()
  ) as Partial<React.ComponentProps<"div">>;

  let nodeRenderer = renderer
    .forNode("checkbox")
    .withVariants(pick(props, ...renderer.getInternalVariantProps()))
    .withVariants(props.variants || {})
    .withArgs(pick(props, ...renderer.getInternalArgProps()))
    .withArgs(props.args || {})
    .withOverrides(pick(props, ...descendantNames))
    .withOverrides(props.overrides || {});

  if (Object.keys(leftoverProps).length > 0) {
    nodeRenderer = nodeRenderer.withOverrides({
      checkbox: {
        props: leftoverProps
      }
    });
  }

  return nodeRenderer.render();
}) as React.FunctionComponent<PlasmicTaskCheckboxProps>;

type PlasmicTaskImgProps = PlasmicTask__VariantsArgs &
  PlasmicTask__ArgsType & {
    variants?: PlasmicTask__VariantsArgs;
    args?: PlasmicTask__ArgsType;
    overrides?: {
      img?: Flex<"img">;
    };

    img?: Flex<"img">;
  } & Omit<
    Partial<React.ComponentProps<"img">>,
    | keyof PlasmicTask__VariantsArgs
    | keyof PlasmicTask__ArgsType
    | "variants"
    | "args"
    | "img"
  >;

PlasmicTask.img = ((props: PlasmicTaskImgProps) => {
  const renderer = new PlasmicTask__Renderer({}, {});
  const descendantNames = ["img"] as const;
  const leftoverProps = omit(
    props,
    "variants",
    "args",
    "overrides",
    ...descendantNames,
    ...renderer.getInternalVariantProps(),
    ...renderer.getInternalArgProps()
  ) as Partial<React.ComponentProps<"img">>;

  let nodeRenderer = renderer
    .forNode("img")
    .withVariants(pick(props, ...renderer.getInternalVariantProps()))
    .withVariants(props.variants || {})
    .withArgs(pick(props, ...renderer.getInternalArgProps()))
    .withArgs(props.args || {})
    .withOverrides(pick(props, ...descendantNames))
    .withOverrides(props.overrides || {});

  if (Object.keys(leftoverProps).length > 0) {
    nodeRenderer = nodeRenderer.withOverrides({
      img: {
        props: leftoverProps
      }
    });
  }

  return nodeRenderer.render();
}) as React.FunctionComponent<PlasmicTaskImgProps>;

type PlasmicTaskLabelProps = PlasmicTask__VariantsArgs &
  PlasmicTask__ArgsType & {
    variants?: PlasmicTask__VariantsArgs;
    args?: PlasmicTask__ArgsType;
    overrides?: {
      label?: Flex<"div">;
    };

    label?: Flex<"div">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicTask__VariantsArgs
    | keyof PlasmicTask__ArgsType
    | "variants"
    | "args"
    | "label"
  >;

PlasmicTask.label = ((props: PlasmicTaskLabelProps) => {
  const renderer = new PlasmicTask__Renderer({}, {});
  const descendantNames = ["label"] as const;
  const leftoverProps = omit(
    props,
    "variants",
    "args",
    "overrides",
    ...descendantNames,
    ...renderer.getInternalVariantProps(),
    ...renderer.getInternalArgProps()
  ) as Partial<React.ComponentProps<"div">>;

  let nodeRenderer = renderer
    .forNode("label")
    .withVariants(pick(props, ...renderer.getInternalVariantProps()))
    .withVariants(props.variants || {})
    .withArgs(pick(props, ...renderer.getInternalArgProps()))
    .withArgs(props.args || {})
    .withOverrides(pick(props, ...descendantNames))
    .withOverrides(props.overrides || {});

  if (Object.keys(leftoverProps).length > 0) {
    nodeRenderer = nodeRenderer.withOverrides({
      label: {
        props: leftoverProps
      }
    });
  }

  return nodeRenderer.render();
}) as React.FunctionComponent<PlasmicTaskLabelProps>;

type PlasmicTaskTextboxProps = PlasmicTask__VariantsArgs &
  PlasmicTask__ArgsType & {
    variants?: PlasmicTask__VariantsArgs;
    args?: PlasmicTask__ArgsType;
    overrides?: {
      textbox?: Flex<"input">;
    };

    textbox?: Flex<"input">;
  } & Omit<
    Partial<React.ComponentProps<"input">>,
    | keyof PlasmicTask__VariantsArgs
    | keyof PlasmicTask__ArgsType
    | "variants"
    | "args"
    | "textbox"
  >;

PlasmicTask.textbox = ((props: PlasmicTaskTextboxProps) => {
  const renderer = new PlasmicTask__Renderer({}, {});
  const descendantNames = ["textbox"] as const;
  const leftoverProps = omit(
    props,
    "variants",
    "args",
    "overrides",
    ...descendantNames,
    ...renderer.getInternalVariantProps(),
    ...renderer.getInternalArgProps()
  ) as Partial<React.ComponentProps<"input">>;

  let nodeRenderer = renderer
    .forNode("textbox")
    .withVariants(pick(props, ...renderer.getInternalVariantProps()))
    .withVariants(props.variants || {})
    .withArgs(pick(props, ...renderer.getInternalArgProps()))
    .withArgs(props.args || {})
    .withOverrides(pick(props, ...descendantNames))
    .withOverrides(props.overrides || {});

  if (Object.keys(leftoverProps).length > 0) {
    nodeRenderer = nodeRenderer.withOverrides({
      textbox: {
        props: leftoverProps
      }
    });
  }

  return nodeRenderer.render();
}) as React.FunctionComponent<PlasmicTaskTextboxProps>;

type PlasmicTaskDeleteBtnProps = PlasmicTask__VariantsArgs &
  PlasmicTask__ArgsType & {
    variants?: PlasmicTask__VariantsArgs;
    args?: PlasmicTask__ArgsType;
    overrides?: {
      deleteBtn?: Flex<"button">;
    };

    deleteBtn?: Flex<"button">;
  } & Omit<
    Partial<React.ComponentProps<"button">>,
    | keyof PlasmicTask__VariantsArgs
    | keyof PlasmicTask__ArgsType
    | "variants"
    | "args"
    | "deleteBtn"
  >;

PlasmicTask.deleteBtn = ((props: PlasmicTaskDeleteBtnProps) => {
  const renderer = new PlasmicTask__Renderer({}, {});
  const descendantNames = ["deleteBtn"] as const;
  const leftoverProps = omit(
    props,
    "variants",
    "args",
    "overrides",
    ...descendantNames,
    ...renderer.getInternalVariantProps(),
    ...renderer.getInternalArgProps()
  ) as Partial<React.ComponentProps<"button">>;

  let nodeRenderer = renderer
    .forNode("deleteBtn")
    .withVariants(pick(props, ...renderer.getInternalVariantProps()))
    .withVariants(props.variants || {})
    .withArgs(pick(props, ...renderer.getInternalArgProps()))
    .withArgs(props.args || {})
    .withOverrides(pick(props, ...descendantNames))
    .withOverrides(props.overrides || {});

  if (Object.keys(leftoverProps).length > 0) {
    nodeRenderer = nodeRenderer.withOverrides({
      deleteBtn: {
        props: leftoverProps
      }
    });
  }

  return nodeRenderer.render();
}) as React.FunctionComponent<PlasmicTaskDeleteBtnProps>;

PlasmicTask.createRenderer = () => new PlasmicTask__Renderer({}, {});

export default PlasmicTask;
/* prettier-ignore-end */
