/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsx createPlasmicElementProxy */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4p2NHB7HnAYV45yx1ZgrVt
// Component: kC6cXBS27C1bHf
import * as React from "react";
import {
  hasVariant,
  createPlasmicElement,
  RenderOpts,
  Override,
  classNames,
  Flex,
  wrapWithClassName,
  Renderer,
  NodeRenderer,
  createPlasmicElementProxy,
  makeFragment,
  PlasmicIcon,
  PlasmicSlot,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger
} from "@plasmicapp/react-web";

import { ThemeContext, ThemeValue } from "../PlasmicGlobalVariant__Theme"; // plasmic-import: qBJztiWboOaDz9/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_todo_mvc_for_tutorial_work.css"; // plasmic-import: 4p2NHB7HnAYV45yx1ZgrVt/projectcss
import "./PlasmicHeader.css"; // plasmic-import: kC6cXBS27C1bHf/css

export type PlasmicHeader__VariantsArgs = {
  state?: SingleChoiceArg<"empty" | "allChecked">;
};

export const PlasmicHeader__VariantProps: (keyof PlasmicHeader__VariantsArgs)[] = [
  "state"
];

export type PlasmicHeader__ArgsType = {};
export const PlasmicHeader__ArgProps: (keyof PlasmicHeader__ArgsType)[] = [];

export interface DefaultHeaderProps {
  state?: SingleChoiceArg<"empty" | "allChecked">;
  className?: string;
}

const PlasmicHeader__RenderFuncs = {
  headerContainer: (
    opts: RenderOpts<
      PlasmicHeader__VariantsArgs,
      PlasmicHeader__ArgsType,
      {
        headerContainer?: Flex<"div">;
        box?: Flex<"div">;
        img?: Flex<"img">;
        textbox?: Flex<"input">;
      }
    >
  ): React.ReactElement | null => {
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};
    return (
      <div
        data-plasmic-override={overrides.headerContainer}
        className={classNames({
          "Header__headerContainer--allChecked__eje8s1Fmf_": hasVariant(
            variants,
            "state",
            "allChecked"
          ),

          "Header__headerContainer--empty__eje8sFQ-je": hasVariant(
            variants,
            "state",
            "empty"
          ),

          Header__headerContainer__eje8s: true,
          "plasmic-default__all": true,
          "plasmic-default__div": true
        })}
      >
        {PlasmicHeader__RenderFuncs.box({
          variants,
          args,
          overrides
        })}

        {PlasmicHeader__RenderFuncs.textbox({
          variants,
          args,
          overrides
        })}
      </div>
    );
  },
  box: (
    opts: RenderOpts<
      PlasmicHeader__VariantsArgs,
      PlasmicHeader__ArgsType,
      {
        box?: Flex<"div">;
        img?: Flex<"img">;
      }
    >
  ): React.ReactElement | null => {
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};
    return (
      <div
        data-plasmic-override={overrides.box}
        className={classNames({
          "Header__box--empty__yEln9FQ-je": hasVariant(
            variants,
            "state",
            "empty"
          ),

          Header__box__yEln9: true,
          "plasmic-default__all": true,
          "plasmic-default__div": true
        })}
      >
        {PlasmicHeader__RenderFuncs.img({
          variants,
          args,
          overrides
        })}
      </div>
    );
  },
  img: (
    opts: RenderOpts<
      PlasmicHeader__VariantsArgs,
      PlasmicHeader__ArgsType,
      {
        img?: Flex<"img">;
      }
    >
  ): React.ReactElement | null => {
    return <PlasmicHeader__FCs.img opts={opts} />;
  },
  textbox: (
    opts: RenderOpts<
      PlasmicHeader__VariantsArgs,
      PlasmicHeader__ArgsType,
      {
        textbox?: Flex<"input">;
      }
    >
  ): React.ReactElement | null => {
    return <PlasmicHeader__FCs.textbox opts={opts} />;
  }
};

const PlasmicHeader__FCs = {
  headerContainer: undefined,
  box: undefined,
  img: ((props: {
    opts: Parameters<typeof PlasmicHeader__RenderFuncs["img"]>[0];
  }) => {
    const { opts } = props;
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};

    const globalVariants = {
      theme: React.useContext(ThemeContext)
    };

    return ((hasVariant(variants, "state", "empty") ? false : true) ? (
      <img
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames({
          "Header__img--allChecked__T0qoG1Fmf_": hasVariant(
            variants,
            "state",
            "allChecked"
          ),

          "Header__img--baseDark__T0qoGFHEdW_6DHL0":
            true && hasVariant(globalVariants, "theme", "dark"),
          "Header__img--empty__T0qoGFQ-je": hasVariant(
            variants,
            "state",
            "empty"
          ),

          Header__img__T0qoG: true,
          "plasmic-default__all": true,
          "plasmic-default__img": true
        })}
        role={"img"}
        src={
          true && hasVariant(globalVariants, "theme", "dark")
            ? ("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAxMiA2IiBoZWlnaHQ9IjYiIHdpZHRoPSIxMiIgc3R5bGU9ImZpbGw6IHJnYigyMTMsIDIwNiwgMjA2KTsiPgo8cGF0aCBmaWxsPSJibGFjayIgZD0iTTAuNjEyIDAuMTEyTDUuODQ0IDMuMjJMMTEuMDc2IDAuMTEyVjIuNUw1Ljg0NCA1LjUyNEwwLjYxMiAyLjQ4OFYwLjExMloiLz4KPC9zdmc+" as const)
            : ("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAxMiA2IiBoZWlnaHQ9IjYiIHdpZHRoPSIxMiI+CjxwYXRoIGZpbGw9ImJsYWNrIiBkPSJNMC42MTIgMC4xMTJMNS44NDQgMy4yMkwxMS4wNzYgMC4xMTJWMi41TDUuODQ0IDUuNTI0TDAuNjEyIDIuNDg4VjAuMTEyWiIvPgo8L3N2Zz4K" as const)
        }
      ></img>
    ) : null) as React.ReactElement;
  }) as React.FunctionComponent<{
    opts: Parameters<typeof PlasmicHeader__RenderFuncs["img"]>[0];
  }>,

  textbox: ((props: {
    opts: Parameters<typeof PlasmicHeader__RenderFuncs["textbox"]>[0];
  }) => {
    const { opts } = props;
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};

    const globalVariants = {
      theme: React.useContext(ThemeContext)
    };

    return (
      <input
        data-plasmic-override={overrides.textbox}
        className={classNames({
          "Header__textbox--allChecked__qDOkE1Fmf_": hasVariant(
            variants,
            "state",
            "allChecked"
          ),

          "Header__textbox--baseDark__qDOkEFHEdW_6DHL0":
            true && hasVariant(globalVariants, "theme", "dark"),
          "Header__textbox--empty__qDOkEFQ-je": hasVariant(
            variants,
            "state",
            "empty"
          ),

          Header__textbox__qDOkE: true,
          "plasmic-default__all": true,
          "plasmic-default__input": true
        })}
        placeholder={"What needs to be done?" as const}
        type={"text" as const}
        value={
          true && hasVariant(globalVariants, "theme", "dark")
            ? ("My Task" as const)
            : undefined
        }
      ></input>
    ) as React.ReactElement;
  }) as React.FunctionComponent<{
    opts: Parameters<typeof PlasmicHeader__RenderFuncs["textbox"]>[0];
  }>
};

class PlasmicHeader__Renderer extends Renderer<
  PlasmicHeader__VariantsArgs,
  PlasmicHeader__ArgsType,
  typeof PlasmicHeader__RenderFuncs,
  "headerContainer"
> {
  constructor(
    variants: PlasmicHeader__VariantsArgs,
    args: PlasmicHeader__ArgsType
  ) {
    super(variants, args, PlasmicHeader__RenderFuncs, "headerContainer");
  }

  protected create(
    variants: PlasmicHeader__VariantsArgs,
    args: PlasmicHeader__ArgsType
  ) {
    return new PlasmicHeader__Renderer(variants, args);
  }

  getInternalVariantProps(): (keyof PlasmicHeader__VariantsArgs)[] {
    return PlasmicHeader__VariantProps;
  }

  getInternalArgProps(): (keyof PlasmicHeader__ArgsType)[] {
    return PlasmicHeader__ArgProps;
  }

  forNode(
    name: "headerContainer"
  ): NodeRenderer<typeof PlasmicHeader__RenderFuncs["headerContainer"]>;
  forNode(name: "box"): NodeRenderer<typeof PlasmicHeader__RenderFuncs["box"]>;
  forNode(name: "img"): NodeRenderer<typeof PlasmicHeader__RenderFuncs["img"]>;
  forNode(
    name: "textbox"
  ): NodeRenderer<typeof PlasmicHeader__RenderFuncs["textbox"]>;
  forNode(name: keyof typeof PlasmicHeader__RenderFuncs) {
    return super.forNode(name);
  }
}

type PlasmicHeaderHeaderContainerProps = PlasmicHeader__VariantsArgs &
  PlasmicHeader__ArgsType & {
    variants?: PlasmicHeader__VariantsArgs;
    args?: PlasmicHeader__ArgsType;
    overrides?: {
      headerContainer?: Flex<"div">;
      box?: Flex<"div">;
      img?: Flex<"img">;
      textbox?: Flex<"input">;
    };

    headerContainer?: Flex<"div">;
    box?: Flex<"div">;
    img?: Flex<"img">;
    textbox?: Flex<"input">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicHeader__VariantsArgs
    | keyof PlasmicHeader__ArgsType
    | "variants"
    | "args"
    | "headerContainer"
    | "box"
    | "img"
    | "textbox"
  >;

export const PlasmicHeader = ((props: PlasmicHeaderHeaderContainerProps) => {
  const renderer = new PlasmicHeader__Renderer({}, {});
  const descendantNames = ["headerContainer", "box", "img", "textbox"] as const;
  const leftoverProps = omit(
    props,
    "variants",
    "args",
    "overrides",
    ...descendantNames,
    ...renderer.getInternalVariantProps(),
    ...renderer.getInternalArgProps()
  ) as Partial<React.ComponentProps<"div">>;

  let nodeRenderer = renderer
    .forNode("headerContainer")
    .withVariants(pick(props, ...renderer.getInternalVariantProps()))
    .withVariants(props.variants || {})
    .withArgs(pick(props, ...renderer.getInternalArgProps()))
    .withArgs(props.args || {})
    .withOverrides(pick(props, ...descendantNames))
    .withOverrides(props.overrides || {});

  if (Object.keys(leftoverProps).length > 0) {
    nodeRenderer = nodeRenderer.withOverrides({
      headerContainer: {
        props: leftoverProps
      }
    });
  }

  return nodeRenderer.render();
}) as React.FunctionComponent<PlasmicHeaderHeaderContainerProps> & {
  box: React.FunctionComponent<PlasmicHeaderBoxProps>;
  img: React.FunctionComponent<PlasmicHeaderImgProps>;
  textbox: React.FunctionComponent<PlasmicHeaderTextboxProps>;
  createRenderer: () => PlasmicHeader__Renderer;
};

type PlasmicHeaderBoxProps = PlasmicHeader__VariantsArgs &
  PlasmicHeader__ArgsType & {
    variants?: PlasmicHeader__VariantsArgs;
    args?: PlasmicHeader__ArgsType;
    overrides?: {
      box?: Flex<"div">;
      img?: Flex<"img">;
    };

    box?: Flex<"div">;
    img?: Flex<"img">;
  } & Omit<
    Partial<React.ComponentProps<"div">>,
    | keyof PlasmicHeader__VariantsArgs
    | keyof PlasmicHeader__ArgsType
    | "variants"
    | "args"
    | "box"
    | "img"
  >;

PlasmicHeader.box = ((props: PlasmicHeaderBoxProps) => {
  const renderer = new PlasmicHeader__Renderer({}, {});
  const descendantNames = ["box", "img"] as const;
  const leftoverProps = omit(
    props,
    "variants",
    "args",
    "overrides",
    ...descendantNames,
    ...renderer.getInternalVariantProps(),
    ...renderer.getInternalArgProps()
  ) as Partial<React.ComponentProps<"div">>;

  let nodeRenderer = renderer
    .forNode("box")
    .withVariants(pick(props, ...renderer.getInternalVariantProps()))
    .withVariants(props.variants || {})
    .withArgs(pick(props, ...renderer.getInternalArgProps()))
    .withArgs(props.args || {})
    .withOverrides(pick(props, ...descendantNames))
    .withOverrides(props.overrides || {});

  if (Object.keys(leftoverProps).length > 0) {
    nodeRenderer = nodeRenderer.withOverrides({
      box: {
        props: leftoverProps
      }
    });
  }

  return nodeRenderer.render();
}) as React.FunctionComponent<PlasmicHeaderBoxProps>;

type PlasmicHeaderImgProps = PlasmicHeader__VariantsArgs &
  PlasmicHeader__ArgsType & {
    variants?: PlasmicHeader__VariantsArgs;
    args?: PlasmicHeader__ArgsType;
    overrides?: {
      img?: Flex<"img">;
    };

    img?: Flex<"img">;
  } & Omit<
    Partial<React.ComponentProps<"img">>,
    | keyof PlasmicHeader__VariantsArgs
    | keyof PlasmicHeader__ArgsType
    | "variants"
    | "args"
    | "img"
  >;

PlasmicHeader.img = ((props: PlasmicHeaderImgProps) => {
  const renderer = new PlasmicHeader__Renderer({}, {});
  const descendantNames = ["img"] as const;
  const leftoverProps = omit(
    props,
    "variants",
    "args",
    "overrides",
    ...descendantNames,
    ...renderer.getInternalVariantProps(),
    ...renderer.getInternalArgProps()
  ) as Partial<React.ComponentProps<"img">>;

  let nodeRenderer = renderer
    .forNode("img")
    .withVariants(pick(props, ...renderer.getInternalVariantProps()))
    .withVariants(props.variants || {})
    .withArgs(pick(props, ...renderer.getInternalArgProps()))
    .withArgs(props.args || {})
    .withOverrides(pick(props, ...descendantNames))
    .withOverrides(props.overrides || {});

  if (Object.keys(leftoverProps).length > 0) {
    nodeRenderer = nodeRenderer.withOverrides({
      img: {
        props: leftoverProps
      }
    });
  }

  return nodeRenderer.render();
}) as React.FunctionComponent<PlasmicHeaderImgProps>;

type PlasmicHeaderTextboxProps = PlasmicHeader__VariantsArgs &
  PlasmicHeader__ArgsType & {
    variants?: PlasmicHeader__VariantsArgs;
    args?: PlasmicHeader__ArgsType;
    overrides?: {
      textbox?: Flex<"input">;
    };

    textbox?: Flex<"input">;
  } & Omit<
    Partial<React.ComponentProps<"input">>,
    | keyof PlasmicHeader__VariantsArgs
    | keyof PlasmicHeader__ArgsType
    | "variants"
    | "args"
    | "textbox"
  >;

PlasmicHeader.textbox = ((props: PlasmicHeaderTextboxProps) => {
  const renderer = new PlasmicHeader__Renderer({}, {});
  const descendantNames = ["textbox"] as const;
  const leftoverProps = omit(
    props,
    "variants",
    "args",
    "overrides",
    ...descendantNames,
    ...renderer.getInternalVariantProps(),
    ...renderer.getInternalArgProps()
  ) as Partial<React.ComponentProps<"input">>;

  let nodeRenderer = renderer
    .forNode("textbox")
    .withVariants(pick(props, ...renderer.getInternalVariantProps()))
    .withVariants(props.variants || {})
    .withArgs(pick(props, ...renderer.getInternalArgProps()))
    .withArgs(props.args || {})
    .withOverrides(pick(props, ...descendantNames))
    .withOverrides(props.overrides || {});

  if (Object.keys(leftoverProps).length > 0) {
    nodeRenderer = nodeRenderer.withOverrides({
      textbox: {
        props: leftoverProps
      }
    });
  }

  return nodeRenderer.render();
}) as React.FunctionComponent<PlasmicHeaderTextboxProps>;

PlasmicHeader.createRenderer = () => new PlasmicHeader__Renderer({}, {});

export default PlasmicHeader;
/* prettier-ignore-end */
